name: Continuous Deployment

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install frontend dependencies
        working-directory: frontend
        run: |
          npm ci

      - name: Build frontend
        working-directory: frontend
        run: |
          npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: frontend

  deploy_backend:
    runs-on: ubuntu-latest
    needs: deploy_frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version

      - name: Install backend dependencies
        working-directory: backend
        run: |
          npm ci

      - name: Run migrations
        working-directory: backend
        run: |
          npm run migrate # Ensure you have a migration script

      - name: Deploy to Render
        uses: render-examples/deploy@v1
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          env: production

  notify:
    runs-on: ubuntu-latest
    needs: [deploy_frontend, deploy_backend]
    steps:
      - name: Notify on deployment success
        run: |
          echo "Deployment successful!" | mail -s "CD Success" your-email@example.com
